### PR TITLE
Rename workshop

### PR DESCRIPTION
**Pull request by inglesp**

### CODE REVIEW

**Comment by alexwlchan** [comment]
I’d like to merge this, but I can’t get it to work locally. 😕 

I get errors when I run `make build`, trying to access `http://localhost:58256/workshops/small-projects-ideas-with-open-data-using-python/`:

```
(2016.pyconuk.org) alexwlchan at Alexs-iMac.local in ~/D/_/2016.pyconuk.org on git:inglesp-rename-workshop
$ make build
python manage.py buildsite
Performing system checks...

System check identified no issues (0 silenced).
September 10, 2016 - 06:54:41
Django version 1.9.7, using settings 'pyconuk.settings'
Starting development server at http://127.0.0.1:58256/
Quit the server with CONTROL-C.
[10/Sep/2016 06:54:42] "GET / HTTP/1.1" 200 9525
Operations to perform:
  Apply all migrations: pyconuk, contenttypes, auth
Running migrations:
  No migrations to apply.
[10/Sep/2016 06:54:44] "GET / HTTP/1.1" 200 9525
[10/Sep/2016 06:54:44] "GET /unlinked-pages/ HTTP/1.1" 200 414
Internal Server Error: /workshops/small-projects-ideas-with-open-data-using-python/
Traceback (most recent call last):
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alexwlchan/Developer/_github/2016.pyconuk.org/pyconuk/views.py", line 159, in session_view
    return render(request, template, context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 1043, in render
    output = self.filter_expression.resolve(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 913, in _resolve_lookup
    current = current()
  File "/Users/alexwlchan/Developer/_github/2016.pyconuk.org/pyconuk/models.py", line 52, in day
    return self.date().split()[0]
  File "/Users/alexwlchan/Developer/_github/2016.pyconuk.org/pyconuk/models.py", line 49, in date
    return self.slot().date
  File "/Users/alexwlchan/Developer/_github/2016.pyconuk.org/pyconuk/models.py", line 43, in slot
    return self.scheduleslot_set.order_by('time')[0]
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/db/models/query.py", line 297, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
[10/Sep/2016 06:54:44] "GET /workshops/small-projects-ideas-with-open-data-using-python/ HTTP/1.1" 500 211210
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django_amber/management/commands/buildsite.py", line 20, in handle
    self.buildsite(port)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django_amber/management/commands/buildsite.py", line 31, in buildsite
    rsp.raise_for_status()
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:58256/workshops/small-projects-ideas-with-open-data-using-python/
make: *** [build] Error 1
```

and if I run `make serve`, it errors on the same page:

<details>
<summary>

Full error from `make serve`</summary>



```
Environment:


Request Method: GET
Request URL: http://localhost:8000/workshops/small-projects-ideas-with-open-data-using-python/

Django Version: 1.9.7
Python Version: 3.5.0
Installed Applications:
['pyconuk',
 'django_amber',
 'markdown_deux',
 'compressor',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.staticfiles']
Installed Middleware:
[]


Template error:
In template /Users/alexwlchan/Developer/_github/2016.pyconuk.org/templates/session.html, error at line 11
   list index out of range   1 : {% extends "base.html" %}
   2 : 
   3 : {% load markdown_deux_tags %}
   4 : 
   5 : {% block content %}
   6 : <article class="main-article">
   7 :   <div class="content">
   8 :     <div class="column_content">
   9 :       <h1>{{ title }}</h1>
   10 : 
   11 :       <p><a href="{% url 'speaker' speaker.key %}">{{ speaker.name }}</a> |  {{ day }}  {{ time }} | {{ room }}</p>
   12 : 
   13 :       <div class="textblock">
   14 :         {% if content_format == 'md' %}
   15 :         {{ content|markdown }}
   16 :         {% else %}
   17 :         {{ content|safe }}
   18 :         {% endif %}
   19 :       </div>
   20 :     </div>
   21 :   </div>


Traceback:

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/alexwlchan/Developer/_github/2016.pyconuk.org/pyconuk/views.py" in session_view
  159.     return render(request, template, context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/shortcuts.py" in render
  67.             template_name, context, request=request, using=using)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/loader.py" in render_to_string
  97.         return template.render(context, request)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/backends/django.py" in render
  95.             return self.template.render(context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py" in render
  206.                     return self._render(context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py" in _render
  197.         return self.nodelist.render(context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py" in render
  992.                 bit = node.render_annotated(context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  959.             return self.render(context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  173.         return compiled_parent._render(context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py" in _render
  197.         return self.nodelist.render(context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py" in render
  992.                 bit = node.render_annotated(context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  959.             return self.render(context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  69.                 result = block.nodelist.render(context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py" in render
  992.                 bit = node.render_annotated(context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  959.             return self.render(context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py" in render
  1043.             output = self.filter_expression.resolve(context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py" in resolve
  709.                 obj = self.var.resolve(context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py" in resolve
  850.             value = self._resolve_lookup(context)

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py" in _resolve_lookup
  913.                             current = current()

File "/Users/alexwlchan/Developer/_github/2016.pyconuk.org/pyconuk/models.py" in day
  52.         return self.date().split()[0]

File "/Users/alexwlchan/Developer/_github/2016.pyconuk.org/pyconuk/models.py" in date
  49.         return self.slot().date

File "/Users/alexwlchan/Developer/_github/2016.pyconuk.org/pyconuk/models.py" in slot
  43.         return self.scheduleslot_set.order_by('time')[0]

File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/db/models/query.py" in __getitem__
  297.         return list(qs)[0]

Exception Type: IndexError at /workshops/small-projects-ideas-with-open-data-using-python/
Exception Value: list index out of range
```

</details>

It passed on Travis, but I’m wondering if Travis would catch this failure – looking at #220, it seems like it might be overly optimistic.

I‘ve updated my local dependencies to no avail – @inglesp any ideas why it works for you and not for me?

**Comment by inglesp** [comment]
Could you try deleting you local database and trying again?

**Comment by alexwlchan** [comment]
I deleted `db.sqlite3` (that’s the only database I need to worry about, right?) and rebuilt; getting a different error on what I think is a deleted workshop?

```
Internal Server Error: /workshops/trolling-on-twitter-with-your-python-bot/
Traceback (most recent call last):
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alexwlchan/Developer/_github/2016.pyconuk.org/pyconuk/views.py", line 159, in session_view
    return render(request, template, context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 1043, in render
    output = self.filter_expression.resolve(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/template/base.py", line 913, in _resolve_lookup
    current = current()
  File "/Users/alexwlchan/Developer/_github/2016.pyconuk.org/pyconuk/models.py", line 52, in day
    return self.date().split()[0]
  File "/Users/alexwlchan/Developer/_github/2016.pyconuk.org/pyconuk/models.py", line 49, in date
    return self.slot().date
  File "/Users/alexwlchan/Developer/_github/2016.pyconuk.org/pyconuk/models.py", line 43, in slot
    return self.scheduleslot_set.order_by('time')[0]
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/db/models/query.py", line 297, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
[10/Sep/2016 07:51:13] "GET /workshops/trolling-on-twitter-with-your-python-bot/ HTTP/1.1" 500 183375
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django_amber/management/commands/buildsite.py", line 20, in handle
    self.buildsite(port)
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/django_amber/management/commands/buildsite.py", line 31, in buildsite
    rsp.raise_for_status()
  File "/Users/alexwlchan/.virtualenvs/2016.pyconuk.org/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:59920/workshops/trolling-on-twitter-with-your-python-bot/
make: *** [build] Error 1

(2016.pyconuk.org) alexwlchan at Alexs-iMac.local in ~/D/_/2016.pyconuk.org on git:inglesp-rename-workshop
$ git status
On branch inglesp-rename-workshop
Your branch is up-to-date with 'origin/inglesp-rename-workshop'.
nothing to commit, working directory clean
```

**Comment by inglesp** [comment]
Ah -- that workshop's deleted on master, but not on this branch.

I've just rebased and force-pushed, so I think it'd now work for you locally.

**Comment by inglesp** [comment]
(I suppose the alternative would have been for you to have merged master into your local branch.)

**Comment by alexwlchan** [comment]
🎉 

Works now, and I see the redirect. Merging.

**Pull request merged**
