### PR TITLE
Apply Steve's 2017 theme

### PR DESCRIPTION
**Pull request by moreati**
A bit rough and ready still, known issues:

- [x] excludes twitter & youtube links in footer
- [x] excludes Blanc Ltd credit
- [x] still has 2016 copyright
- [x] sponsors' logos will need additional styling information to be gridded correctly
- [x] "Show speakers" checkbox on the schedule does nothing
- [x] Doesn't use lessc to regenerate css

### CODE REVIEW

**Comment by inglesp** [comment]
Thanks @moreati for looking at this.  Generally it looks pretty good!  Seeing the design with content has made it clear to me that we'll only want to use the picture City Hall and the three snakes on the homepage, but we don't need to make this change for the 2016 site.

There are a handful things that I think we'll need to fix before we start using this design:

* [ ] The font doesn't display apostrophes well -- see the "We're", "won't", "We'll" in this image:
image
* [x] There are two footers -- one with the copyright notice and the other with the company address.  Moving the contents of the `<footer>` inside the `<div class="small">` is probably an acceptable solution, but somebody with a better design eye might be able to come up with something better.
* [x] The page headings are too small, and get lost in the big red background.
* [x] The yellow snake's crown is missing!

There are also some less important things that should be addressed, but which aren't as urgent.

* [x] We don't have rooms on the mobile version of the schedule
* [x] For some screen widths, the blue snake's hat obscures the dates of the conference.
image
* [ ] The mouse can be placed in such a way that the snakes flicker up and down.

@moreati How much more work were you planning to put into this?  Specifically, which of the known issues that you've highlighted above were you expecting @hawkz to work on?

@hawkz When do you think you'll get the chance to take a look at this again?

**Comment by moreati** [comment]
I've addressed most of the review comments.

@inglesp your call whether the remaining items are release blockers.

**Comment by inglesp** [comment]
This is looking great, thanks @moreati!

I think the apostrophes are a release blocker.  @hawkz, can you suggest another font?

**Comment by inglesp** [comment]
Also the yellow snake's crown is back, but I think it's the wrong one -- compare

image

with

image

which was in the original design.

**Comment by moreati** [comment]
> Also the yellow snake's crown is back, but I think it's the wrong one -- compare
> {white crown}
> with
> {black crown}
> which was in the original design.

~~To clarify, by original design do you mean the 2016 website, or Steve's 2017 design? The later is white, I didn't change that.~~

Scratch that, yes I did

**Comment by inglesp** [comment]
Hurrah, all the hats are back.

It also looks like the apostrophe problem can be solved by using `'` rather than `’`, so I think I'm happy to say this is done.  I'll close this and apply the styling etc to the new site this week.

Thanks again @moreati and @hawkz!

**Pull request closed without merging**
