### PR TITLE
Add Code of Conduct

### PR DESCRIPTION
**Pull request by inglesp**
Addresses https://github.com/PyconUK/pyconuk-2016-internaldocs/issues/30.

### CODE REVIEW

**Comment by Lukasa** [comment]
This looks good to me, but it's kinda a big deal so I would like one other review before merging..

**Comment by doismellburning** [comment]
Diffing on phone is hard, but I can't see any delta from the source documents - is there?

LGTM!

**Comment by inglesp** [comment]
@doismellburning -- there's no delta from the source documents.  Doing so usefully would be a bit fiddly, because of formatting questions, but I can provide one if you'd like.

**Comment by doismellburning** [comment]
Sorry, my intent was fairly ambiguous in hindsight! I'll try again:

This looks like an exact copy of the source docs. If so, yep, awesome, let's do it. If not, I'm curious about what got changed, BUT as far as I can see, I'm still happy with it.

**Comment by doismellburning** [comment]
@inglesp On that basis, I believe @Lukasa and I heartily endorse what you're doing here, so let's!

**Pull request merged**
