### PR TITLE
Don't build site if any page errors

### PR DESCRIPTION
**Pull request by inglesp**
One for @ghickman, given earlier discussion.

### CODE REVIEW

**Comment by inglesp** [comment]
The fact this has just failed is a good thing!

**Comment by inglesp** [comment]
This should go green once https://github.com/PyconUK/2016.pyconuk.org/pull/221 is merged.

**Comment by alexwlchan** [comment]
#221 is merged, so if somebody gives Travis a nudge we should be able to get this merged as well.

**Comment by inglesp** [comment]
I've nudged.

**Comment by alexwlchan** [comment]
This is the Travis failure:

<details>
<summary>

<code>[09/Sep/2016 18:06:19] "GET /static/img/logos/psf.png HTTP/1.1" 404 98</code></summary>



```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django_amber/management/commands/buildsite.py", line 20, in handle
    self.buildsite(port)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django_amber/management/commands/buildsite.py", line 31, in buildsite
    rsp.raise_for_status()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:54234/static/img/logos/psf.png
make[1]: *** [build] Error 1
```

</details>

I can’t seem to reproduce this error locally – when I check out this branch and run `./pre-flight-checks.sh`, it exits cleanly. Is it Travis with the dodgy setup, or me?

**Comment by inglesp** [comment]
I _can_ reproduce this locally.  I have a hunch that the problem's caused by `DEBUG` being `False`, causing problems with static file handling.

Yes: running `DEBUG=yes ./pre-flight-checks.sh` succeeds.

I don't have the time _right now_ to look into this.  Fortunately, @doismellburning has forgotten more than I'll ever know about serving static files with Django (I've got a mental block about them), and @ghickman's pretty handy too.

(What I really don't understand is why I was able to build the site with this code yesterday, and why you're able to build it now.  Investigating that is probably a red herring though.)

**Comment by doismellburning** [comment]
Currently I know nothing about amber, will fix that between this comment and the next

Looks like this relied on `runserver`'s automatic static file serving due to `DEBUG` being `True` - aiui Django here just acts as a service run at build time from which static files are crawled, so you can probably just use https://docs.djangoproject.com/en/1.10/howto/static-files/#serving-static-files-during-development but it's not immediately clear to me whether this is something to be changed in Amber or in this...

**Comment by ghickman** [comment]
I've rebased this branch on top of my tweak to master (serve static with `DEBUG=True`).

My fix/hack makes Django serve static files when we build without DEBUG.

@doismellburning – if you wouldn't mind having a quick look to make sure I haven't done anything really silly with static then merging?

**Comment by doismellburning** [comment]
Hacktastically beautiful

**Pull request merged**
