### PR TITLE
Initial draft of session chairing notes.

### PR DESCRIPTION
**Pull request by Lukasa**
Feedback requested!

### CODE REVIEW

**Comment by alexwlchan** [comment]
A few thoughts on build/style matters:
- I fetched the branch, built the site, went to `/session-chairing/`, and… nothing. Scratched my head a bit – then spotted there’s a typo in the name of the file. "chairing", not "charing".
- I think it would help if the sub-points had a different numbering scheme, e.g. (a), (b), (c). Can be achieved with the following LESS rule in `styles.less`:

``` less
ol ol {
  list-style-type: lower-alpha;
}
```
- Does this need to be added to the list of unlinked pages in `views.py`? I thought I’d seen something about pages not being built if they weren’t added there – but this page shows up okay.

**Comment by inglesp** [comment]
Content's great, thanks.

You'll need to add the name of the page to the list in `unlinked_pages_view`: https://github.com/PyconUK/2016.pyconuk.org/blob/master/pyconuk/views.py#L279.

**Comment by Lukasa** [comment]
Ok, so far I've made every change except for the style change. Do we still want it?

**Comment by meatballs** [comment]
> Ok, so far I've made every change except for the style change. Do we still want it?

I'd rather have the content right now so I can point people at it. Tidying up style can come later.

**Comment by alexwlchan** [comment]
> I'd rather have the content right now so I can point people at it. Tidying up style can come later.

Agreed.

**Pull request merged**
