### PR TITLE
Add link to sprints page to schedule

### PR DESCRIPTION
**Pull request by kragniz**

### CODE REVIEW

**Comment by kragniz** [comment]
Not sure if this is the 'right' way to add links, but I just copied what djangogirls does in the schedule.

**Comment by alexwlchan** [comment]
Couple of things:
- For this to show up, we need to run `python manage.py parseschedule` and check in the auto-generated files. Yes, checking in autogen files is sub-par, but it’s what we have and it works.
- I have a nasty feeling this will cause the sprints to fall off the calendar – I think we exclude talks whose “title” starts with a `<`.

I can fix both of these if you don’t have time, but it’ll have to wait until I get home.

**Comment by kragniz** [comment]
Look better now?

**Comment by inglesp** [comment]
:+1:

**Pull request merged**
