### PR TITLE
Changes in Dive into Object-oriented Python workshop

### PR DESCRIPTION
**Pull request by lgiordani**
Added the address of the code repository for the Dive into Object-oriented Python workshop

### CODE REVIEW

**Comment by alexwlchan** [comment]
I’m going to merge this anyway with broken tests (just the check for the spelling of “PyCon UK” that’s a bit confused), and then immediately commit a fix.

**Comment by alexwlchan** [comment]
Thanks @lgiordani!

**Comment by lgiordani** [comment]
Sorry for the spelling error!

**Comment by alexwlchan** [comment]
@lgiordani Not your fault – we have something that checks “PyCon UK” isn’t misspelt, but it got confused because you had “PyConUK2016” in a URL. Nothing to worry about. 😄

**Pull request merged**
