### PR TITLE
Add copy for home page

### PR DESCRIPTION
**Pull request by inglesp**
This adds text for the homepage.  When reviewing, don't worry about broken links for now.

Addresses https://github.com/PyconUK/pyconuk-2016-internaldocs/issues/26.

### CODE REVIEW

**Comment by Lukasa** [comment]
What's going on with the escaped punctuation in the markdown?

**Comment by inglesp** [comment]
It's deliberate -- I thought that proper apostrophes and dashes looked a bit nicer.

**Comment by Lukasa** [comment]
=P Fair enough, I guess our Markdown renderer doesn't do that for us?

**Comment by inglesp** [comment]
Must not be merged until we're ready to launch, since it'll trample over the current "coming soon" page!

**Comment by inglesp** [comment]
Closing in favour of https://github.com/PyconUK/2016.pyconuk.org/pull/12.

**Pull request closed without merging**
