### PR TITLE
Add copy for teachers' day page

### PR DESCRIPTION
**Pull request by inglesp**
Addresses https://github.com/PyconUK/pyconuk-2016-internaldocs/issues/53.

### CODE REVIEW

**Comment by inglesp** [comment]
Carrie Anne has said that she's happy with this content.

**Comment by snim2** [comment]
Is this ready to be merged?

**Comment by inglesp** [comment]
I think so, as are the others at https://github.com/PyconUK/2016.pyconuk.org/pulls.

**Comment by snim2** [comment]
OK, I will go through them. The text here looks fine. I am a little concerned that we will forget to deal with the `TODOs` before we go live though.

**Comment by inglesp** [comment]
Good point!  Have created https://github.com/PyconUK/pyconuk-2016-internaldocs/issues/59 to make sure we do this, but feel free to raise individual issues if you spot anything.

**Pull request merged**
